name: material_design_lite
version: 1.1.1-dev.1
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: Material Design Lite JS, CSS and fonts
homepage: https://github.com/rwl/material_design_lite
